export const PATIENT_LIST_REQUEST = "PATIENT_LIST_REQUEST";
export const PATIENT_LIST_SUCCESS = "PATIENT_LIST_SUCCESS";
export const PATIENT_LIST_FAIL = "PATIENT_LIST_FAIL";
export const PATIENT_LIST_RESET = "PATIENT_LIST_RESET";

export const PATIENT_DETAILS_REQUEST = "PATIENT_DETAILS_REQUEST";
export const PATIENT_DETAILS_SUCCESS = "PATIENT_DETAILS_SUCCESS";
export const PATIENT_DETAILS_FAIL = "PATIENT_DETAILS_FAIL";

export const PATIENT_DELETE_REQUEST = "PATIENT_DELETE_REQUEST";
export const PATIENT_DELETE_SUCCESS = "PATIENT_DELETE_SUCCESS";
export const PATIENT_DELETE_FAIL = "PATIENT_DELETE_FAIL";

export const PATIENT_CREATE_REQUEST = "PATIENT_CREATE_REQUEST";
export const PATIENT_CREATE_SUCCESS = "PATIENT_CREATE_SUCCESS";
export const PATIENT_CREATE_FAIL = "PATIENT_CREATE_FAIL";
export const PATIENT_CREATE_RESET = "PATIENT_CREATE_RESET";

export const PATIENT_UPDATE_REQUEST = "PATIENT_UPDATE_REQUEST";
export const PATIENT_UPDATE_SUCCESS = "PATIENT_UPDATE_SUCCESS";
export const PATIENT_UPDATE_FAIL = "PATIENT_UPDATE_FAIL";
export const PATIENT_UPDATE_RESET = "PATIENT_UPDATE_RESET";

export const PATIENT_CREATE_BLOODPRESSURE_REQUEST =
  "PATIENT_CREATE_BLOODPRESSURE_REQUEST";
export const PATIENT_CREATE_BLOODPRESSURE_SUCCESS =
  "PATIENT_CREATE_BLOODPRESSURE_SUCCESS";
export const PATIENT_CREATE_BLOODPRESSURE_FAIL =
  "PATIENT_CREATE_BLOODPRESSURE_FAIL";
export const PATIENT_CREATE_BLOODPRESSURE_RESET =
  "PATIENT_CREATE_BLOODPRESSURE_RESET";

export const PATIENT_CREATE_HEARTRATE_REQUEST =
  "PATIENT_CREATE_HEARTRATE_REQUEST";
export const PATIENT_CREATE_HEARTRATE_SUCCESS =
  "PATIENT_CREATE_HEARTRATE_SUCCESS";
export const PATIENT_CREATE_HEARTRATE_FAIL = "PATIENT_CREATE_HEARTRATE_FAIL";
export const PATIENT_CREATE_HEARTRATE_RESET = "PATIENT_CREATE_HEARTRATE_RESET";

export const PATIENT_CREATE_BLOODSUGAR_REQUEST =
  "PATIENT_CREATE_BLOODSUGAR_REQUEST";
export const PATIENT_CREATE_BLOODSUGAR_SUCCESS =
  "PATIENT_CREATE_BLOODSUGAR_SUCCESS";
export const PATIENT_CREATE_BLOODSUGAR_FAIL = "PATIENT_CREATE_BLOODSUGAR_FAIL";
export const PATIENT_CREATE_BLOODSUGAR_RESET =
  "PATIENT_CREATE_BLOODSUGAR_RESET";

export const PATIENT_CREATE_SATURATION_REQUEST =
  "PATIENT_CREATE_SATURATION_REQUEST";
export const PATIENT_CREATE_SATURATION_SUCCESS =
  "PATIENT_CREATE_SATURATION_SUCCESS";
export const PATIENT_CREATE_SATURATION_FAIL = "PATIENT_CREATE_SATURATION_FAIL";
export const PATIENT_CREATE_SATURATION_RESET =
  "PATIENT_CREATE_SATURATION_RESET";

export const PATIENT_CREATE_COMMENT_REQUEST = "PATIENT_CREATE_COMMENT_REQUEST";
export const PATIENT_CREATE_COMMENT_SUCCESS = "PATIENT_CREATE_COMMENT_SUCCESS";
export const PATIENT_CREATE_COMMENT_FAIL = "PATIENT_CREATE_COMMENT_FAIL";
export const PATIENT_CREATE_COMMENT_RESET = "PATIENT_CREATE_COMMENT_RESET";
